language: python
python:
- '3.6'
node_js:
- 4.8
branches:
  only:
  - prod

before_install:
- pip install pytest-cov
- npm install cypress --save-dev
install:
- pip install -r requirements.txt

jobs:
  include:
  - stage: "Microservices Tests"
    script:
      - pytest ./Tests/test_Microservice.py
  
  - stage: "Authentication Tests"
    script:
      - pytest ./Tests/test_AuthDB.py
      - pytest ./Tests/integrated_test_AuthDB.py

  - stage: Cypress Tests
    script:
    - python3 ./Model/WebServer/backend.py & APP_PID=$!
    - python3 ./Model/Microservice/Microservice.py & APP_PID=$!
    - "$(npm bin)/cypress run"

stages:
- Microservices Tests
- Authentication Tests
- Cypress Tests 

after_success:
deploy:
provider: gae
keyfile: client-secret.json
project: avid-circle-257318
on: prod