language: python
python:
- '3.6'
node_js:
- 4.8
branches:
  only:
  - prod

before_install:
- pip install pytest-cov
- npm install cypress --save-dev
install:
- pip install -r requirements.txt

jobs:
  include:
  
  - stage: End-To-End Tests
    script:
    - python3 ./Model/WebServer/backend.py & APP_PID=$!
    - python3 ./Model/Microservice/Microservice.py & APP_PID=$!
    - python3 ./Model/WebServer/admin_backend.py & APP_PID=$!
    - "$(npm bin)/cypress run"
    
  - stage: Deploy to GAE
    deploy:
    provider: gae
    keyfile: client-secret.json
    config:
      - app.yaml
      - microservice.yaml
      - admin.yaml
    project: avid-circle-257318
    on: prod

stages:
- End-To-End Tests 
- Deploy to GAE