language: python
python:
  - "3.6"
branches:
  # whitelist
  only:
<<<<<<< HEAD
    - travis_ci_test
=======
    - milestone1_submition
>>>>>>> Created .travis.yml file for CI testing
# command to install dependencies
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "Microservices Tests"
      script: 
        - pytest ./Tests/test_Apple.py
        - pytest ./Tests/test_Facebook.py
        - pytest ./Tests/test_Google.py
        - pytest ./Tests/test_Oracle.py
        - pytest ./Tests/test_Ubisoft.py

    - stage: "Database Tests"
      script: 
        - pytest ./Tests/test_LogDatabase.py
        - pytest ./Tests/test_Logger.py

    - stage: "Authentication Tests"
      script: 
        - pytest ./Tests/test_AuthDB.py
      
stages:
  - Microservices Tests
  - Database Tests
  - Authentication Tests