language: python
python:
- '3.6'
node_js:
- 4.8
branches:
  only:
  - milestone2_travis_integration
addons:
  apt:
    packages:
    - ca-certificates
before_install:
- openssl aes-256-cbc -K $encrypted_1981fd0afa44_key -iv $encrypted_1981fd0afa44_iv
  -in client-secret.json.enc -out client-secret.json -d
- pip install pytest-cov
- npm install cypress --save-dev
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: Cypress Tests
    script:
    - python3 ./Model/WebServer/backend.py & APP_PID=$!
    - python3 ./Model/Microservice/Microservice.py & APP_PID=$!
    - "$(npm bin)/cypress run"
stages:
- Cypress Tests
deploy:
  provider: gae
  keyfile: "..."
  project: avid-circle-257318
  on: milestone2_travis_integration
