language: python
python:
  - "3.6"
branches:
  # whitelist
  only:
    - travis_ci_test
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: pytest
jobs:
  include:
    - stage: "Microservices"
      script: pytest ./Tests/test_Apple.py
      script: pytest ./Tests/test_Facebook.py
      script: pytest ./Tests/test_Google.py
      script: pytest ./Tests/test_Oracle.py
      script: pytest ./Tests/test_Ubisoft.py
stages:
  - Microservices

