language: python
python:
  - "3.6"
branches:
  # whitelist
  only:
    - travis_ci_test
# command to install dependencies
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: "Microservices"
        script: pytest test_Apple.py
        script: pytest test_Facebook.py
        script: pytest test_Google.py
        script: pytest test_Oracle.py
        script: pytest test_Ubisoft.py


