matrix:
  include:
    - language: python
      python: 
        - 3.7
      branches:
        only:
          - travis_ci_test
      before_install:
        - pip install pytest-cov
      install: 
        - pip install -r requirements.txt
      script:
        - pytest ./Tests/test_Apple.py

    - language: node_js
      node_js:
        - 4.8
      before_install:
        - npm install cypress --save-dev

notifications:
  email:
    - moolchanddanny@hotmail.com