<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Testing Travis-CI #1
language: python
python:
  - "3.6"
branches:
  # whitelist
  only:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    - travis_ci_test
<<<<<<< HEAD
=======
    - milestone1_submition
>>>>>>> Created .travis.yml file for CI testing
=======
    - travis_ci_test
>>>>>>> Travis-CI Branch Only
=======

before_install:
  - pip install pytest-cov
  - sudo apt-get install python3-distutils

>>>>>>> Testing Code Coverage v0.1
# command to install dependencies
install:
  - pip install -r requirements.txt
=======
matrix:
  include:
    - language: python
      python: 
        - 3.7
      branches:
        only:
          - travis_ci_test
      before_install:
        - pip install pytest-cov
<<<<<<< HEAD
      install: 
        - pip install -r requirements.txt

      jobs:
      include:
        - stage: "Microservices Tests"
          script: 
            - pytest ./Tests/test_Apple.py
            - pytest ./Tests/test_Facebook.py
            - pytest ./Tests/test_Google.py
            - pytest ./Tests/test_Oracle.py
            - pytest ./Tests/test_Ubisoft.py
>>>>>>> Testing New Travis YML file

        - stage: "Database Tests"
          script: 
            - pytest ./Tests/test_LogDatabase.py
            - pytest ./Tests/test_Logger.py

        - stage: "Authentication Tests"
          script: 
            - pytest ./Tests/test_AuthDB.py

        - stage: "Coverage Report"
          script: 
            - pytest --cov=Tests/

      stages:
        - Microservices Tests
        - Database Tests
        - Authentication Tests
        - Coverage Report
=======
      # install: 
      #   # - pip install -r requirements.txt
      script:
        - pytest ./Tests/test_Apple.py
>>>>>>> cypress

    - language: node_js
      node_js:
        - 4.8
      before_install:
        - npm install cypress --save-dev

notifications:
  email:
    - moolchanddanny@hotmail.com
=======
=======
<<<<<<< refs/remotes/origin/authentication
<<<<<<< HEAD
>>>>>>> Created .travis.yml file for CI testing
=======
<<<<<<< refs/remotes/origin/authentication
>>>>>>> Travis-CI Branch Only
    - travis_ci_test
<<<<<<< refs/remotes/origin/authentication
=======
    - milestone1_submition
>>>>>>> Created .travis.yml file for CI testing
=======
    - travis_ci_test
>>>>>>> Travis-CI Branch Only
=======

before_install:
  - pip install pytest-cov
  - sudo apt-get install python3-distutils

>>>>>>> Testing Code Coverage v0.1
# command to install dependencies
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "Microservices Tests"
      script: 
        - pytest ./Tests/test_Apple.py
        - pytest ./Tests/test_Facebook.py
        - pytest ./Tests/test_Google.py
        - pytest ./Tests/test_Oracle.py
        - pytest ./Tests/test_Ubisoft.py

<<<<<<< HEAD
>>>>>>> Testing Travis-CI #1
=======
    - stage: "Database Tests"
      script: 
        - pytest ./Tests/test_LogDatabase.py
        - pytest ./Tests/test_Logger.py

    - stage: "Authentication Tests"
      script: 
        - pytest ./Tests/test_AuthDB.py

    - stage: "Coverage Report"
      script: 
        - pytest --cov=Tests/

stages:
  - Microservices Tests
  - Database Tests
  - Authentication Tests
<<<<<<< HEAD
>>>>>>> More Stages
=======
  - Coverage Report
>>>>>>> Covergae v0.3
