language: python
python:
  - "3.6"
node_js:
  - 4.8

branches:
  # whitelist
  only:
    - travis_ci_test

addons:
  apt:
    packages:
      - ca-certificates

before_install:
  - pip install pytest-cov
  - npm install cypress --save-dev

# command to install dependencies
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "Authentication Tests"
      script: 
        - pytest ./Tests/test_AuthDB.py

    - stage: "Cypress Tests"
      script: 
        - python3 ./Model/WebServer/backend.py & APP_PID=$!
        - $(npm bin)/cypress run
        - kill APP_PID

stages:
  - Authentication Tests
  - Cypress Tests