language: python
python:
- '3.6'
node_js:
- 4.8
branches:
  only:
  - milestone2_travis_integration

before_install:
- pip install pytest-cov
- npm install cypress --save-dev
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: Cypress Tests
    script:
    - python3 ./Model/WebServer/backend.py & APP_PID=$!
    - python3 ./Model/Microservice/Microservice.py & APP_PID=$!
    - "$(npm bin)/cypress run"
stages:
- Cypress Tests
deploy:
  provider: gae
  keyfile: client-secret.json
  project: avid-circle-257318
  on: milestone2_travis_integration