runtime: python37
<<<<<<< HEAD
=======
env: flex
>>>>>>> milestone2_travis_integration

entrypoint: gunicorn -b :$PORT main:app

# [START handlers]
handlers:
- url: /(.*)
  script: auto
# [END handlers]