runtime: python37

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  API_KEY: "AIzaSyCBNsjeqTwLByOJdGKqaY5VyWvcjJe8UTY"

# [START handlers]
handlers:
- url: /.*
  script: auto
# [END handlers]